### ISSUE TITLE
/osbuilder/rootfs.sh: line 154: make: command not found

### ISSUE THREAD

**Issue by liyingjun** [kata-containers/osbuilder#43] opened 2018-01-25 03:01 UTC
When building rootfs for centos using command:
export USE_DOCKER=true
./rootfs-builder/rootfs.sh -r "${PWD}/centos_rootfs" centos

failed with: /osbuilder/rootfs.sh: line 154: make: command not found

**Comment by bergwolf** [comment] 2018-01-25 09:04
Hi @liyingjun, I can confirm the error locally and I see that you already have a patch for it. Can you please make a PR? Thanks!

**Comment by liyingjun** [comment] 2018-01-25 09:10
@bergwolf  PR https://github.com/kata-containers/osbuilder/pull/40 fixes the issue

**Comment by jodh-intel** [comment] 2018-03-21 11:23
Closing as it sounds like the issue is now resolved.

**Closed by jodh-intel** 2018-03-21 11:23 UTC
